config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts
  resources :users, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :body, presence: true, length: { minimum: 5, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  validates :username, presence: true, length: { minimum: 3, maximum: 30 }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @posts = Post.all
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "Successfully #{@post.title} is created..."
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "Successfully #{@post.title} is updated..."
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Successfully #{@post.title} is deleted..."
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def require_same_user
    return if current_user == @post.user

    flash[:alert] = 'You can edit or destroy only your own post.'
    redirect_to @post
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="mt-5 py-2 bg-light text-center">
  <small>&copy; <a href="https://github.com/yocosaka" target="_blank">sakayoco</a></small>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "My Members", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to  "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Members", users_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.username %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "See Profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Delete Account", user_registration_path, method: :delete, data: { confirm: 'Are you sure to delete you account?' }, class: "dropdown-item" %>
        </div>
      </li>
      <% end %>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <div class="my-2 my-lg-0">
      <% if user_signed_in? %>
        <%= link_to  "Sign out", destroy_user_session_path, class: "btn btn-outline-success", method: :delete %>
      <% else %>
        <%= link_to  "Sign up", new_user_registration_path, class: "btn btn-success" %>
        <%= link_to  "Sign in", new_user_session_path, class: "btn btn-outline-success"  %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

<% if alert %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong><%= alert %></strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMembers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container-fluid">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render "shared/errors", obj: @post %>
<%= form_with(model: @post, local: true, class: 'form')  do |f| %>
  <div class="field mb-3">
    <%= f.label :title, "Title", { class: "form-label" } %> <br>
    <%= f.text_field :title, { class: "form-control"} %>
  </div>

  <div class="field mb-3">
    <%= f.label :body, "Body", { class: "form-label" } %> <br>
    <%= f.text_area :body, { class: "form-control"} %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<div class="col-12 col-md-6 col-xl-4">
  <div class="card text-center">
    <% if user_signed_in? %>
      <div class="card-header">
        Posted by <%= gravatar_image_tag(post.user.email.gsub('spam', 'mdeering'), size: 15, alt: post.user.username, class: "thumb" ) %> <%= link_to  post.user.username, user_path(post.user) %>
      </div>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.body %></p>
      <%= link_to "See this post", post_path(post), class:"btn btn-primary" %>
    </div>
    <div class="card-footer text-muted">
      Posted <%= distance_of_time_in_words(post.created_at, Time.now) %> ago
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container-fluid my-5">
  <h1>Edit a post</h1>
  <%= render "posts/form" %>
</div>

app/views/posts/index.html.erb
<h1>All the posts</h1>
<% if @posts.any? %>
<div class="container-fluid">
  <div class="row">
    <%= render partial: "post", collection: @posts %>
  </div>
</div>
<% else %>
  <p>Not found</p>
<% end %>

<% if user_signed_in? %>
  <%= link_to  "Create a new post", new_post_path, class: "btn btn-dark btn-lg" %>
<% end %>

app/views/posts/new.html.erb
<div class="container-fluid my-5">
  <h1>Create a new post</h1>
  <%= render "posts/form" %>
</div>

app/views/posts/show.html.erb
<div class="container-fluid text-center my-5">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title"><%= @post.title %></h1>
      <h5 class="card-subtitle mb-2 text-muted">Posted by <%= gravatar_image_tag(@post.user.email.gsub('spam', 'mdeering'), size: 15, alt: @post.user.username, class: "thumb" ) %> <%= link_to  @post.user.username, user_path(@post.user) %></h5>
      <p class="card-text"><%= @post.body %></p>

      <p>Posted <%= distance_of_time_in_words(@post.created_at, Time.now) %> ago</p>
      <% if @post.user == current_user %>
        <%= link_to  "Edit this post", edit_post_path(@post), class: "btn btn-primary" %>
        <%= link_to  "Delete this post", post_path(@post), class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/_user.html.erb
<div class="col-3">
  <div class="card">
    <%= gravatar_image_tag(user.email.gsub('spam', 'mdeering'), size: 15, alt: user.username, class: "member-pic" ) %>
    <div class="card-body">
      <h5 class="card-title"><%= user.username %></h5>
      <%= link_to  "See this member", user_path(user), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>All Members</h1>

<% if @users.any? %>
<div class="container">
  <div class="row">
  <%= render partial: "user", collection: @users %>
  </div>
</div>
<% else %>
  <p>Not found</p>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid text-center my-5">
  <h1><%= @user.username %></h1>
  <%= gravatar_image_tag(@user.email.gsub('spam', 'mdeering'), size: 200, alt: @user.username, class: "pic" ) %>

  <% if @user == current_user  %>
  <div class="">
    <%= link_to  "Edit account", edit_user_registration_path, class: "btn btn-primary" %>
    <%= link_to "Delete Account", user_registration_path, method: :delete, data: { confirm: 'Are you sure to delete you account?' }, class: "btn btn-danger" %>
  </div>
  <% end %>
</div>

<% if @user.posts.any? %>
  <div class="container-fluid">
    <div class="row">
      <%= render partial: "posts/post", collection: @user.posts %>
    </div>
  </div>
<% end %>